# Generated by Django 2.1.5 on 2019-02-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandeep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('image', models.FileField(upload_to='static/img/profile/')),
                ('about', models.TextField(null=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(max_length=30)),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
