# Generated by Django 2.1.5 on 2019-02-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandeep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='user_id',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='projects',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='users',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
