# Generated by Django 2.1.5 on 2019-02-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandeep', '0003_auto_20190202_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(upload_to='static/img/profile/'),
        ),
    ]
